# Generated by Django 6.0.4 on 2026-04-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='gallery',
        ),
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
