# Generated by Django 6.0.4 on 2026-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicelocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
