# Generated by Django 5.2.1 on 2026-04-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_category_sub_category_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
