# Generated by Django 5.2.1 on 2026-04-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_plan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
    ]
