# Generated by Django 5.2.1 on 2026-04-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_country_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.ManyToManyField(blank=True, to='service.city'),
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.ManyToManyField(blank=True, to='service.country'),
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='service.subcategory'),
        ),
    ]
