# Generated by Django 5.2.1 on 2026-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0015_remove_customuser_role_idx_remove_customuser_photo_and_more'),
        ('service', '0010_service_city_service_country_service_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='auths.socialmedia'),
        ),
    ]
