# Generated by Django 5.2.1 on 2026-04-27 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_service_social_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addon_type', models.CharField(choices=[('front_page_listing', 'Front Page Listing'), ('top_profile_placement', 'Top Profile Placement'), ('additional_location', 'Additional Location'), ('additional_categories', 'Additional Categories'), ('additional_bumps', '2 Additional Bumps')], max_length=50, unique=True)),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_limit', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.addon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
