# Generated by Django 5.2.1 on 2026-04-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_addon_useraddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
