# Generated by Django 5.2.7 on 2025-10-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_customuser_date_of_birth_alter_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
