# Generated by Django 5.2.7 on 2025-10-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_remove_customuser_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
