# Generated by Django 5.2.7 on 2025-10-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
