# Generated by Django 5.2.7 on 2025-10-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpUsImprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improve_message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improving', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
