# Generated by Django 6.0.4 on 2026-04-20 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0012_remove_customuser_designation_and_more'),
        ('service', '0002_remove_service_gallery_service_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.subscription'),
        ),
    ]
