# Generated by Django 5.2.1 on 2026-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0014_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='role_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[('bliss', 'BLISS'), ('beauty', 'BEAUTY')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_image',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_with_image',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='licence_image',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
