# Generated by Django 5.2.7 on 2025-10-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dashboard', max_length=50)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
            },
        ),
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
