# Generated by Django 5.2.7 on 2025-10-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_home', '0002_dashboarddummy_delete_dummymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddummy',
            name='name',
        ),
    ]
